### ISSUE TITLE
No such file or directory: '/tmp/build/80754af9/numpy_and_numpy_base_1603487797006/work'

### ISSUE THREAD

**Issue by lixiangMindSpore** [hrlblab/CircleNet#10]
![image](https://user-images.githubusercontent.com/78945582/150748828-c1567333-0b67-4cb7-bb51-257838ac465d.png)

**Comment by EthanHNguyen** [comment]
Hi lixiang! 

Try replacing the "requirements.txt" file with the following.


> bbox==0.9.2
> certifi==2021.5.30
> cffi
> cycler==0.10.0
> Cython==0.29.24
> kiwisolver==1.3.1
> llvmlite==0.36.0
> matplotlib==3.3.4
> mkl-fft
> mkl-random
> mkl-service
> numba==0.53.1
> numpy 
> olefile==0.46
> opencv-python==4.5.2.54
> openslide-python==1.1.2
> Pillow 
> progress==1.5
> pycocotools==2.0
> pycparser
> pyparsing==2.4.7
> pyquaternion==0.9.9
> python-dateutil==2.8.1
> scipy==1.5.4
> six
> xmltodict==0.12.0

**Comment by EthanHNguyen** [comment]
@lixiangMindSpore Has the issue been resolved?
