### ISSUE TITLE
转COCO数据集格式请教

### ISSUE THREAD

**Issue by lixiangMindSpore** [hrlblab/CircleNet#12]
> The nuclei dateset with annotation file can be found here: https://github.com/hrlblab/CircleNet/blob/master/docs/DATA.md

1  在COCO格式的注释里，annotations中的segmentation字段多出了如下图所示的内容，其中width和height在image字段中已经出现了，如果直接用circlenet直接训练的话，这个必须加吗？
![image](https://user-images.githubusercontent.com/78945582/154029672-36ad7482-4c3f-431d-a154-475a14567c6a.png)

2  extreme_points代表什么意思？
3  MoNuSeg_extreme_train2021.json和MoNuSeg_train2021.json有什么区别？

**Comment by lixiangMindSpore** [comment]
麻烦专家解答一下，不胜感激！

**Comment by EthanHNguyen** [comment]
No worries! 

(1) This is indeed extra information. You should only need circle center and circle radius.

(2) The extreme points are for a baseline method (ExtremeNet: https://github.com/xingyizhou/ExtremeNet) if you would like to reproduce our results. You can read their paper to understand it, but it is not needed for CircleNet.

(3) MoNuSeg_extreme_train2021.json has the extreme points calculated. MoNuSeg_train2021.json does not have extreme points.

**Comment by lixiangMindSpore** [comment]
> MoNuSeg_train2021.json

专家您好，谢谢您的解答，还有几个疑问：
1  在MoNuSeg_train2021.json中有extreme points字段，如下图所示
![image](https://user-images.githubusercontent.com/78945582/154382840-dc938e34-0ab3-4890-bb8d-da9bfd88a7f9.png)
2  如果extreme points这个字段我不需要，在MoNuSeg_train2021.json中我就默认这个字段的值？还是删除该字段？

**Comment by hrlblab** [comment]
Dear Sir, please ask questions in English so that we and other users can understand. The first author of this work does not understand Chinese. Thanks

**Comment by EthanHNguyen** [comment]
Thanks, please use English. 

You should be able to delete the extreme points if only using CircleNet.

**Comment by lixiangMindSpore** [comment]
> No worries!
> 
> (1) This is indeed extra information. You should only need circle center and circle radius.
> 
> (2) The extreme points are for a baseline method (ExtremeNet: https://github.com/xingyizhou/ExtremeNet) if you would like to reproduce our results. You can read their paper to understand it, but it is not needed for CircleNet.
> 
> (3) MoNuSeg_extreme_train2021.json has the extreme points calculated. MoNuSeg_train2021.json does not have extreme points.

You just said MoNuSeg_train2021.json does not have extreme points, however, I found extreme points in this MoNuSeg_train2021.json. What's wrong? Thank you so much!
![image](https://user-images.githubusercontent.com/78945582/154881223-fc8b6f9c-a53b-41a6-9704-f53a3e1b24e3.png)

**Comment by EthanHNguyen** [comment]
My mistake. MoNuSeg_train2021.json does not require extreme points but is included for convenience.

**Comment by lixiangMindSpore** [comment]
> My mistake. MoNuSeg_train2021.json does not require extreme points but is included for convenience.
> […](#)
> On Feb 21, 2022, at 3:00 AM, lixiangMindSpore ***@***.***> wrote: No worries! (1) This is indeed extra information. You should only need circle center and circle radius. (2) The extreme points are for a baseline method (ExtremeNet: https://github.com/xingyizhou/ExtremeNet <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxingyizhou%2FExtremeNet&data=04%7C01%7Cethan.h.nguyen%40mail-service-3-mx.vanderbilt.edu%7C50eb0016ce3545b1482508d9f4e64629%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637810092137641560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=scyhEQMRTxIN62dWKrQ1JaH%2BD1bwFkGT7mfu%2BgBfG%2FI%3D&reserved=0>) if you would like to reproduce our results. You can read their paper to understand it, but it is not needed for CircleNet. (3) MoNuSeg_extreme_train2021.json has the extreme points calculated. MoNuSeg_train2021.json does not have extreme points. You just said MoNuSeg_train2021.json does not have extreme points, however, I found extreme points in this MoNuSeg_train2021.json. What's wrong? Thank you so much! <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F78945582%2F154881223-fc8b6f9c-a53b-41a6-9704-f53a3e1b24e3.png&data=04%7C01%7Cethan.h.nguyen%40mail-service-3-mx.vanderbilt.edu%7C50eb0016ce3545b1482508d9f4e64629%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637810092137641560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ob2IK5yzGzwfKfquiRODG911Lo5pKmHW8gQRRwX%2B%2FIM%3D&reserved=0> — Reply to this email directly, view it on GitHub <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhrlblab%2FCircleNet%2Fissues%2F12%23issuecomment-1046423176&data=04%7C01%7Cethan.h.nguyen%40mail-service-3-mx.vanderbilt.edu%7C50eb0016ce3545b1482508d9f4e64629%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637810092137641560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3K6mEPEdSfJ%2BEL38m8z6i1nGYRoxx9CDnBZKb5RoG%2Fs%3D&reserved=0>, or unsubscribe <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFQ7ZQY6FAXLM7AWSQYLXULU4GTDTANCNFSM5ON4EOSA&data=04%7C01%7Cethan.h.nguyen%40mail-service-3-mx.vanderbilt.edu%7C50eb0016ce3545b1482508d9f4e64629%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637810092137641560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EQZji5C8k8cjEuQM56E4LJL5stR3wgVF53vldoc5Leo%3D&reserved=0>. Triage notifications on the go with GitHub Mobile for iOS <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cethan.h.nguyen%40mail-service-3-mx.vanderbilt.edu%7C50eb0016ce3545b1482508d9f4e64629%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637810092137641560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=V7oiKiXaVg2SBqM5hlY0mSnq5xiXNIh%2Biz34Y8ZrWuU%3D&reserved=0> or Android <https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cethan.h.nguyen%40mail-service-3-mx.vanderbilt.edu%7C50eb0016ce3545b1482508d9f4e64629%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C637810092137641560%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=67fX7CK7XlA1BVKfiox7oZsVeO7U4dR4%2BlVAMjcPUnU%3D&reserved=0>. You are receiving this because you commented.

Thank you so much!
