### ISSUE TITLE
Some questions of training

### ISSUE THREAD

**Issue by lixiangMindSpore** [hrlblab/CircleNet#13]
Now, I have my own COCO format dataset. I would like to train my own dataset. I intend to know the specific of command.

https://github.com/hrlblab/CircleNet/blob/master/experiments/circledet_monuseg_dla.sh
In circledet_monuseg_dla.sh, what's the meaning of exp_id? I have searched  the key word "CircleNet_DLA_Reproduce" in the whole project, but I can't find the related code.
![image](https://user-images.githubusercontent.com/78945582/154922932-cb8cf3e8-5f1c-4753-90a7-7c67265c93ac.png)

**Comment by EthanHNguyen** [comment]
exp_id is the name of the project you would like. You can put any name your would like.
