### ISSUE TITLE
windows

### ISSUE THREAD

**Issue by LKHZ** [hrlblab/CircleNet#15]
Is it available on Windows?

**Comment by EthanHNguyen** [comment]
Hi @LKHZ. Thanks for your interest in our project.

Unfortunately, we do not have experience using CircleNet on windows but it may work with some workarounds. The project is based on CenterNet. You can find their workaround [here](https://github.com/xingyizhou/CenterNet/issues/7)

**Comment by EthanHNguyen** [comment]
There is also a Google Colab notebook you can use: https://github.com/hrlblab/CircleNet/blob/master/src/circle_net_demo.ipynb

**Comment by LKHZ** [comment]
Ok,thank you!
Does 'Google Colab' run locally?

**Comment by LKHZ** [comment]
> 

![image](https://user-images.githubusercontent.com/70903631/176844810-aa5400d8-14d6-4482-bec6-2154cff57984.png)
I don't know why this issue?

**Comment by LKHZ** [comment]
My environment is configured, but I have some confusion about the data set. I don't quite understand the information represented by some indexes in the JSON file, could you please explain it.
![image](https://user-images.githubusercontent.com/70903631/176893996-d98f6101-f3d0-48fc-bd3f-9458e24beaa6.png)

**Comment by EthanHNguyen** [comment]
> Ok,thank you! Does 'Google Colab' run locally?

Not natively. You can probably adapt the code to run natively.

If you're just experimenting with the code, then I recommend using Google Colab. let me know if you need help setting it up.

**Comment by EthanHNguyen** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/70903631/176844810-aa5400d8-14d6-4482-bec6-2154cff57984.png) I don't know why this issue?

What version of CUDA are you using?

**Comment by EthanHNguyen** [comment]
> but I have some confusion about the data set. I don't quite understand the information represented by some indexes in the JSON file, could you please explain it.

Yes, no worries. The JSON file follows COCO convention. Our JSON contains some extra annotations but here are the important ones for CircleNet. Each `id` describes one annotated object.
* `area` : how much area the segmentation takes up
* `bbox`: the bounding box of the annotated object
* `segmentation`: the annotated segmentation of the objects
* `extreme_points`: not used in circlenet but rather extremenet. Describes the min/max x,y points
* `iscrowd`: not  used in circlenet but rather for panoptic segmentation

You can read [this article](https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch) to  understand how COCO annotations are generated.

**Comment by LKHZ** [comment]
Thank you very much for your reply. I have made clear about the coco data set. Now I have made my own data set, and the training is to run **main.py** file is OK? Then evaluate the model and run the **demo.py** file?

**Comment by EthanHNguyen** [comment]
Yes, that works. You can also look at this file for the training and test commands I use.

https://github.com/hrlblab/CircleNet/blob/master/experiments/circledet_monuseg_dla.sh

**Comment by EthanHNguyen** [comment]
You can also use `main.py` to train, test, and create visualizations. To see the options, take a look at [this file](https://github.com/hrlblab/CircleNet/blob/master/src/lib/opts.py).

**Comment by LKHZ** [comment]
I have a new question, Can demo.py only run one image? I set the --demo path as a folder, but it only displays one image. I don't quite understand. 
I'm looking forward to your reply.

**Comment by EthanHNguyen** [comment]
I haven't used `demo.py` to run a folder of images. Try setting [this](https://github.com/hrlblab/CircleNet/blob/2e8f557c1d8c2b6b63ad462eaa1139d9bd1c2273/src/lib/opts.py#L31) parameter.

Let me know if that does not work, and I'll be happy to look more carefully into it.

**Comment by LKHZ** [comment]
OK, after setting the parameters, it can be displayed normally.

Thank you very much for your reply.
