### ISSUE TITLE
Running demo.ipynb

### ISSUE THREAD

**Issue by XiaobingDean** [hrlblab/CircleNet#17]
Hi, I have followed all your steps on demo.ipynb, but when I run the final command, it show this kind of error. How do I solve it. And is there new version for CUDA 10.1 10.2 or 9.1 to run this code.
![777a014e550553dd6a27cc6ed9cdb99](https://user-images.githubusercontent.com/77907333/192135771-157d422c-61fc-4b5a-a66b-c67d8b2eafe0.jpg)

**Comment by EthanHNguyen** [comment]
Hi, thanks for checking our repository. 

(1) I haven’t seen this error before. Have you changed the circledet.py file? Are you using a custom dataset? 
(2) There’s no new version of CUDA that we tried.

**Comment by XiaobingDean** [comment]
Hi, thanks for responding. I am using a new dataset instead of just demoing, will this be the reason why it doesn't work?

**Comment by EthanHNguyen** [comment]
Yes, it might be one reason that it doesn’t work. The dataset need to be in a specific format — let me know if you need help converting it.

I’ve run into some issues compiling the dependencies. I would recommend reproducing our results first. This page has the dataset and model we use. 
https://github.com/hrlblab/CircleNet/blob/master/docs/GETTING_STARTED.md

**Comment by XiaobingDean** [comment]
Thanks for your help, I am doing it now and I will keep you updated.

**Comment by XiaobingDean** [comment]
![1664100226640](https://user-images.githubusercontent.com/77907333/192138107-a322fae5-c0ef-4d0f-8d76-b1ddc431e65d.jpg)
Hi, I am running your first command on https://github.com/hrlblab/CircleNet/blob/master/docs/GETTING_STARTED.md, and I got this error. Could you help me with this?

**Comment by EthanHNguyen** [comment]
Did you do the dataset set-up? The error means it can read in the input.

**Comment by EthanHNguyen** [comment]
*can not read in the data

**Comment by XiaobingDean** [comment]
Hi, I have successfully run the demo one, thanks for your help.
