### ISSUE TITLE
Changing the input size

### ISSUE THREAD

**Issue by EugeneKok97** [hrlblab/CircleNet#18]
Hi, I was trying to train CircleNet on my custom dataset with the image resolution of 128. I managed to train the NN with this following command:
```python main.py circledet --exp_id Apple2 --arch hourglass --batch_size 4 --master_batch 4 --lr 2.5e-4  --dataset apple --load_model /home/lmga-titanx/CircleNet/src/lib/models/ctdet_coco_hg.pth --input_res 128 --input_h 128 --input_w 128 --num_epochs 200```

However, when I tried to run detection with my trained model using the following script:

```MODEL_PATH = '/home/lmga-titanx/CircleNet/exp/circledet/Apple2/model_best.pth'
TASK = 'circledet'
opt = opts().init('{} --dataset {} --load_model {} --arch {} --input_w {} --input_h {} --K {}'.format(TASK, 'coco', MODEL_PATH, 'hourglass', 128,128, 1).split(' '))

detector = detector_factory[opt.task](opt)
ret = detector.run(img)['results']
```

It returns an output that seemingly corresponds to the resolution of 512:
```
{1: array([[356.9697   , 344.58255  , 263.82367  ,   0.7991894,   0.       ]],
      dtype=float32)}
```

Can you please let me know what I may have done incorrectly? Thank you!

**Comment by EthanHNguyen** [comment]
Hi EugeneKok97,

Thanks for your interest in our research.

The parameters look right to me.

Unfortunately, we only tested CircleNet with 512 x 512 pixel images. However, our code is based on [CenterNet](https://github.com/xingyizhou/CenterNet) which allows for different resolutions. You may need to write additional code, but I am sure you can modify the network architecture to take images of different resolution similar to how CenterNet accomplishes it.
