### ISSUE TITLE
Hi,I want to use other dataset instead of MoNuSeg2021,but the circle_center and circle_radius fields are not in the json file. How do I get them

### ISSUE THREAD

**Issue by AKshang** [hrlblab/CircleNet#19]
### for example
**Our dataset no circle_center and circle_radius fields in json file**       {"id": 1326, "image_id": 12, "category_id": 1, "iscrowd": 0, "area": 693, "bbox": [303.0, 270.0, 38.0, 30.0], "segmentation": [[337.0, 299.5, 315.0, 297.5, 305.0, 293.5, 302.5, 284.0, 307.5, 271.0, 314.0, 270.5, 324.0, 282.5, 331.0, 284.5, 333.0, 279.5, 340.5, 293.0, 337.0, 299.5]], "width": 500, "height": 500} 

**The monuseg2021 dataset you provided have circle_center and circle_radius fields**           {"id": 65786, "image_id": 309, "category_id": 1, "iscrowd": 0, "area": 191, "bbox": [393.0, 305.0, 19.0, 14.0], "segmentation": [[410.0, 318.5, 395.0, 314.5, 392.5, 309.0, 398.0, 304.5, 405.0, 305.5, 411.5, 312.0, 410.0, 318.5]], "width": 512, "height": 512, **"circle_center": [401.583984375, 313.134765625], "circle_radius": 9.980734386753602,** "extreme_points": [[398, 304], [392, 309], [410, 318], [411, 312]]}

**Comment by EthanHNguyen** [comment]
Hi AKshang,

Thanks for your interest in our research. This is a great question.

I just uploaded the file we use to convert from COCO to CircleNet format: [https://github.com/hrlblab/CircleNet/blob/4e0a8063d3591787e022d18427d258c3c20c237f/src/tools/COCO_to_CircleNet.py](https://github.com/hrlblab/CircleNet/blob/4e0a8063d3591787e022d18427d258c3c20c237f/src/tools/COCO_to_CircleNet.py)

Let me know if you have any questions

**Comment by AKshang** [comment]
> Hi AKshang,
> 
> Thanks for your interest in our research. This is a great question.
> 
> I just uploaded the file we use to convert from COCO to CircleNet format: https://github.com/hrlblab/CircleNet/blob/4e0a8063d3591787e022d18427d258c3c20c237f/src/tools/COCO_to_CircleNet.py
> 
> Let me know if you have any questions

Thank you！The present problem has been solved

**Comment by AKshang** [comment]
Thank you！The present problem has been solved 

| |
zxdneau
|
|
***@***.***
|
---- Replied Message ----
| From | Ethan ***@***.***> |
| Date | 11/6/2022 02:06 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hrlblab/CircleNet] Hi,I want to use other dataset instead of MoNuSeg2021,but the circle_center and circle_radius fields are not in the json file. How do I get them (Issue #19) |

Hi AKshang,

Thanks for your interest in our research. This is a great question.

I just uploaded the file we use to convert from COCO to CircleNet format: https://github.com/hrlblab/CircleNet/blob/4e0a8063d3591787e022d18427d258c3c20c237f/src/tools/COCO_to_CircleNet.py

Let me know if you have any questions
