### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by czifan** [hrlblab/CircleNet#2]
Hello, your work has helped me a lot!!! 
May I ask if the glomerular detection dataset in this paper can be provided privately.
Thanks u~

**Comment by chpp123** [comment]
Thank you for your open source code. If you can send me the dataset privately, it will have a great impact on my work. Thank you very much again.

**Comment by NCHUPP18170877081** [comment]
If the dataset is inconvenient to publish, I hope to give pointers on the annotation of the dataset. It is best to provide an annotation file, thank you！！！

**Comment by EthanHNguyen** [comment]
Sorry, we cannot provide the glomerular detection dataset. However, I will provide a similar nuclei dataset soon.

**Comment by EthanHNguyen** [comment]
The nuclei dateset can be found here: https://github.com/hrlblab/CircleNet/blob/master/docs/DATA.md
