### ISSUE TITLE
Unable to download [circledet_monuseg_hg]

### ISSUE THREAD

**Issue by oldliyoungli** [hrlblab/CircleNet#22]

**Comment by EthanHNguyen** [comment]
Should be fixed now. Thanks!

[Model Zoo](https://github.com/hrlblab/CircleNet/blob/master/docs/MODEL_ZOO.md)

**Comment by oldliyoungli** [comment]
unable to open the website   ( https://vanderbilt.app.box.com/s/a487y8swbjssfogtpbpnb8wsn50fvdm3)

**Comment by EthanHNguyen** [comment]
That’s interesting — it works on my end without any credentials.


Can you access box.com <http://box.com/>?

**Comment by oldliyoungli** [comment]
unfortunately ,i can not open http://box.com/   ,That's my problem.    thanks!!

**Comment by weljouni** [comment]
Unable to download circledet_monuseg_hg or https://github.com/hrlblab/CircleNet/blob/master/experiments/circledet_monuseg_dla.sh from https://github.com/hrlblab/CircleNet/blob/master/docs/MODEL_ZOO.md or https://vanderbilt.app.box.com/s/a487y8swbjssfogtpbpnb8wsn50fvdm3 

Can you help?
