### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Fortuneteller6** [hrlblab/CircleNet#24]
How could i get the data of circle_center and circle_radius in a new dataset? Use the labelImg, it can only get the bbox data.

**Comment by Fortuneteller6** [comment]
I use the labelme to mark the data yesterday, and rebulid the labelme2voc.py to get the needed data. Then write the voc2coco.py, making the data of voc format to be what the monuseg/coco dataset like.

**Comment by syf997819611** [comment]
Could you please share the "labelme2voc.py" and "voc2coco.py" files with me？

**Comment by Fortuneteller6** [comment]
> Could you please share the "labelme2voc.py" and "voc2coco.py" files with me？

Please provide me with an email address.

**Comment by syf997819611** [comment]
3462694535@qq.com,thank you very much
