### ISSUE TITLE
Dataset Annotation Format

### ISSUE THREAD

**Issue by NCHUPP18170877081** [hrlblab/CircleNet#4]
If the dataset is inconvenient to publish, I hope to give pointers on the annotation of the dataset. It is best to provide an annotation file, thank you！！！

**Comment by EthanHNguyen** [comment]
Hi,

Sorry for the late reply, the format of the annotation is COCO. You can find a good tutorial here: https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch.

For CircleNet, you just need to add additional fields for center point and radius for the circle representation of each object.

**Comment by EthanHNguyen** [comment]
The nuclei dateset with annotation file can be found here: https://github.com/hrlblab/CircleNet/blob/master/docs/DATA.md

**Comment by lixiangMindSpore** [comment]
> The nuclei dateset with annotation file can be found here: https://github.com/hrlblab/CircleNet/blob/master/docs/DATA.md

在COCO格式的注释里，annotations中的segmentation字段多出了如下图所示的内容，其中width和height在image字段中已经出现了，如果直接用circlenet直接训练的话，这个必须加吗？
![image](https://user-images.githubusercontent.com/78945582/154029672-36ad7482-4c3f-431d-a154-475a14567c6a.png)
