### ISSUE TITLE
hello，你们circledet这里面的radius loss要怎么理解呢，output['wh']就可以理解为预测的半径，batch['cl']为GT的半径吗

### ISSUE THREAD

**Issue by booooming** [hrlblab/CircleNet#5]
https://github.com/hrlblab/CircleNet/blob/020b23082c757f0a995a5b75379307ed52ce1e81/src/lib/trains/circledet.py#L27

**Comment by booooming** [comment]
cl_loss += self.crit_reg(
                        output['cl'], batch['reg_mask'],
                        batch['ind'], batch['cl']) / opt.num_stacks
这个输入有四项，shape也都不是一样的，请问这是如何计算loss的呢

**Comment by hrlblab** [comment]
Thanks for playing with the code. You can email ethan.h.nguyen@Vanderbilt.Edu for such details. Thanks
