### ISSUE TITLE
专家您好，CircleNet如何进行训练，训练命令是什么？

### ISSUE THREAD

**Issue by lixiangMindSpore** [hrlblab/CircleNet#7]
专家您好，CircleNet如何进行训练，训练命令是什么？

**Comment by EthanHNguyen** [comment]
An overview of training can be found here: https://github.com/hrlblab/CircleNet/blob/master/docs/DEVELOP.md

Here's an example of training commands: https://github.com/hrlblab/CircleNet/blob/master/experiments/circledet_monuseg_dla.sh
