### ISSUE TITLE
专家您好，circlenet的算力GFLOPs有多大？

### ISSUE THREAD

**Issue by lixiangMindSpore** [hrlblab/CircleNet#8]

**Comment by EthanHNguyen** [comment]
I don't understand your question. Can you please rephrase your question and provide an example?

**Comment by lixiangMindSpore** [comment]
> I don't understand your question. Can you please rephrase your question and provide an example?

![image](https://user-images.githubusercontent.com/78945582/150302538-f4b2913e-a7df-4f56-a3a3-a8ab5df361d4.png)

**Comment by EthanHNguyen** [comment]
I am not familiar with calculating FLOPs. However, CircleNet is based on CenterNet, and you can find speed comparisons here: https://arxiv.org/abs/1904.07850. 

From the code, you can also calculate it.
