### ISSUE TITLE
How to solve this problem:  No module named 'models.networks.DCNv2._ext'

### ISSUE THREAD

**Issue by lixiangMindSpore** [hrlblab/CircleNet#9]
![image](https://user-images.githubusercontent.com/78945582/150742905-86842fac-51df-40e3-ac79-9cd8b7417b46.png)

**Comment by EthanHNguyen** [comment]
Thanks for your interest in our project! Were you able to successfully compile DCNv2?

[Install.MD](https://github.com/hrlblab/CircleNet/blob/master/docs/INSTALL.md)

> 6. Compile deformable convolutional (from DCNv2).
> cd $CircleNet_ROOT/src/lib/models/networks/DCNv2git 
> ./make.sh

**Comment by EthanHNguyen** [comment]
Also, what version of CUDA are you using? I have had issues with DCNv2 when my CUDA version doesn't match the PyTorch one.

**Comment by EthanHNguyen** [comment]
@lixiangMindSpore Has the issue been resolved?
